from .loader import Loader
from .fashion_mnist import FashionMnist
from .tiny_imagenet import TinyImageNet
from .mnist import MNIST
from .usps import USPS
from .cifar import CIFAR
from .pubfig import PubFig
from .flower import Flower
from .spam import Spam